language: python
cache: pip
python:
    - "2.7"
  # - "2.6"
  # - "3.4"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "pypy"
install:
    - pip install flake8
    # flake8 drops support for py2.6 in v3.0
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install flake8==2.6.2;  fi
before_script:
    - flake8 .
script:
    - python setup.py install
    - ./scripts/download_data_GRCh37.sh
    - python ./run_index.py
    - pip install -r requirements.txt
    - python setup.py nosetests
