language: python
python:
          - "2.7"
install:
          - pip install flake8
          - pip install coveralls
before_script:
          - flake8 .
script:
          - nosetests --with-coverage --cover-package=veppy
after_success:
          - coveralls
